### ISSUE TITLE
Link to pretrained proSRGAN

### ISSUE THREAD

**Issue by phiresky** [fperazzi/proSR#1]
Hey! Amazing paper.

There is a link to pretrained proSR model in the get_data script (`wget https://www.dropbox.com/s/hlgunvtmkvylc4h/proSR.pth?dl=0`) and a link to proSRs pretrained model in the README (`https://www.dropbox.com/s/ldv397lcr3vn95w/proSRs.zip?dl=0`). But I am not seeing a link to the `proSRGAN` model. Is this intentional, accidental, or am I missing something? :)

**Comment by SecondFlight** [comment]
I haven't looked at the code or anything, but I think this is what you're looking for:

http://igl.ethz.ch/projects/prosr/ProSRGAN.zip

**Comment by phiresky** [comment]
From what I can tell, that ZIP only contains the data used, not a
pretrained model

Am Fr., 7. Sep. 2018 um 14:54 Uhr schrieb Joshua Wade <
notifications@github.com>:

**Comment by SecondFlight** [comment]
Ah, okay. That's unfortunate :/

**Comment by fperazzi** [comment]
Hey guys, thanks for your interest in our work. We haven't added the code for GAN training yet, and the old model needs to be migrated from pytorch 0.3.0 to 0.4.0. Expect updates in the upcoming two weeks.

**Comment by yifita** [comment]
working on it :)

**Comment by nazariyv** [comment]
Can't wait for the GAN version. Thank you :)

**Comment by fperazzi** [comment]
I just uploaded the GAN models. There is also a train_gan.py script in the `dev` branch, in case you want to train it yourself.

**Comment by rahidz** [comment]
Downloaded the pre-trained models (thanks!), is it intentional for there not to be a model for x2, just x4 and x8?

**Comment by fperazzi** [comment]
Yes, I don't have the x2.

**Comment by yifita** [comment]
> Downloaded the pre-trained models (thanks!), is it intentional for there not to be a model for x2, just x4 and x8?



> > Downloaded the pre-trained models (thanks!), is it intentional for there not to be a model for x2, just x4 and x8?
> 
> No, we don't provide the x2 models.

Hi, actually both models work quite well for x2.

**Comment by fperazzi** [comment]
Just FYI, GAN training is available in the `dev` branch. I'll merge soon to master.
