### ISSUE TITLE
Pytorch CPU Utilization

### ISSUE THREAD

**Issue by adamantek** [fperazzi/proSR#13]
I've been having an issue with running out of memory when upscaling images. Small-medium images are fine at 2X but trying to Scale toX 4 and 8X leads to the memory issue. I'm assuming this is because when upscaling to 8X, the card keeps the 2X and subsequently 8X image in memory. Will running the python script with the --CPU option enabled offload some of the memory requirements to the system or is it still limited to my CUDA device (GTX 970) with 4gigs?

**Comment by scotshinderman** [comment]
@adamantek  w/ the --cpu flag I saw memory spike also.  Sometimes ~20gig depending on the model

**Comment by fperazzi** [comment]
Can you try setting`num_workers` in `DataLoader` to 0?

**Comment by melvinroest** [comment]
I'm not sure if you're using Docker, but in my case, I needed to set my memory requirements higher. See https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container

I still ran out of memory though (20 GB).
