### ISSUE TITLE
Pretrained model's standard deviation is odd

### ISSUE THREAD

**Issue by nurtdinovadf** [fperazzi/proSR#16]
Hi!

While trying out your pretrained models I found that input values after transformations were odd, ranging from ~(-150 to 150).
And it seemed like standard deviation values were the cause,  [0.0039215, 0.0039215, 0.0039215]. Were they meant to be like that?

**Comment by fperazzi** [comment]
Yes, not sure why though. @yifita might have a better explanation. The standard deviation above is equivalent to [1/255,1/255,1/255]. This value is used to scale RGB images from range [0,1] to ~ [-127.5, 127.5].

**Comment by yifita** [comment]
We used the same normalization values like the NTIRE2017 winner EDSR. https://github.com/LimBee/NTIRE2017

**Comment by nurtdinovadf** [comment]
Thanks!
