### ISSUE TITLE
TypeError: `torch.Device' object is not callable

### ISSUE THREAD

**Issue by sylido** [fperazzi/proSR#17]
Trying to get this project to run with the --cpu parameter gives me this error. Any idea what might have gone wrong here ?

As for CUDA I'm getting a runtime error 35 - CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:51 - I made sure to install CUDA 9.1 and the nVidia driver that supports it. Seems like there is an issue with Cuda 9.1 and the current driver. Maybe porting to use CUDA 10 might make it easier to test.

**Comment by fperazzi** [comment]
Please post the stack trace of this error.

**Comment by spocky** [comment]
As I had the exact same issue, I thought I'd post the stack trace
`Traceback (most recent call last):
  File "test.py", line 76, in <module>
    checkpoint = torch.load(args.checkpoint,map_location=torch.device('cpu'))
  File "/home/spocky/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/spocky/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/home/spocky/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/home/spocky/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 323, in restore_location
    result = map_location(storage, location)
TypeError: 'torch.Device' object is not callable
`

**Comment by fperazzi** [comment]
Great, thanks for fixing the issue.

**Comment by fperazzi** [comment]
@sylido: which version of the CUDA drivers do you have installed? I have 9.2.

**Comment by sylido** [comment]
@fperazzi I followed the guide so I assume cuda91 through conda. With that said it was throwing that error and I did try to install cuda 9.1 through nvidia. I think I had the 340 driver and I tried upgrading to the one specified for 9.1 but it seems to have gotten 3834.145 at least that's what nvidia-smi gives me. When I do nvcc --version I get 9.1, 9.1.85 - so I'll try 9.2 and update if that helps. Thanks for the help !

**Comment by sylido** [comment]
Installed 9.2 and the driver that comes with it - had to still nuke my conda environment and re-did the steps - now works just fine ! thanks @fperazzi

**Comment by fperazzi** [comment]
@sylido thanks a lot for sharing your solution. In summary, cpu version requires CUDA 9.2?

**Comment by sylido** [comment]
@fperazzi nope, the cpu version is fixed by @spocky PR that you merged in.

The gpu version needed some love and care with the proper nvidia driver and CUDA 9.2 - also nuking the conda envrionment and setting it up again.
