### ISSUE TITLE
Q: Real-time higher-res images (like a movie?)

### ISSUE THREAD

**Issue by danger89** [fperazzi/proSR#18]
Hi,

I was wondering is it possible with proSR to create **_real-time_** 2x or 4x higher resolution from a video stream of 512x448 pixels with let's say 20 or 30 FPS?

Real-time, I mean a stream of input data, which creates a stream of output data (eg. like a movie as input).

Kind regards,
Melroy

**Comment by mexicantexan** [comment]
It's definitely possible, but you would have to do some fancy coding and threading to make it happen.
