### ISSUE TITLE
non integer resolution multiples?

### ISSUE THREAD

**Issue by amanmeetgarg** [fperazzi/proSR#20]
Hi @yifita @fperazzi  
Thank you for sharing the very concise implementation. I am working on a dataset where the image scale factor from HR/LR is 1.5 and 2.25.
I am having a hard time wrapping my head around how would I get it to work on these data.
I am limited as the original HR images are in 4:3 aspect ratio and need to be upsampled in the same aspect ratio ..

Any thoughts on how this would come across in the proSR or proGANSR model ?

Thanks.

**Comment by fperazzi** [comment]
@amanmeetgarg, a solution is to pre-upscale or post-downscale the images with a bicubic filter. I.e.: if the target upscaling factor is 1.5x, I would upscale 2x and downsample to the desired resolution. If your target resolution is 2.25, pre-upscale the input image by a factor of 1.125.
