### ISSUE TITLE
GPU memory limit workaround

### ISSUE THREAD

**Issue by Shadetail** [fperazzi/proSR#21]
Hi! I'm new to github and I'm not a real programmer, but I solved the GPU memory limit issue by writing a python script that splits the image into many small images (with padding to avoid seams), automatically runs all the pieces through ProSR and then puts them all back together into a final upscaled image.

What would be the best way to share this with everyone so that it is easy to find for people who might need it? Somehow add it into this project? Create new project on github? Just leave it here?

Anyways, this is the code:

```
upscale = 4         # 4 or 8
padding = 128     # default = 128

fullgrid = [] #initializing these as lists so that we can access crop data to reconstruct images later
gridx = []
gridy = []

import shutil
import os
import math
from skimage import io #for cropping
from PIL import Image #for importing
import subprocess #for calling the main script
import glob
import sys

path = 'input'
filenames = [f for f in os.listdir(path)] #put names for all files in input directory to filenames array

image_list = [] #open all images in input directory into an image_list array
for filename in glob.glob('input/*'):
    im=Image.open(filename)
    image_list.append(im)
    print ('loaded image:',im)

imagenumber = 0
for image in image_list: #cycle through each image, cropping it into smaller images
    print ('cropping image', filenames[imagenumber])
    imagenumber += 1
    gridx.append(math.floor((image.size[0]-1)/padding)) #find number of horizontal crops
    gridy.append(math.floor((image.size[1]-1)/padding)) #find number of vertical crops
    # -1 is for cases when width or height are multiples of padding,
    # or in other words, becasue image resolution starts with row 1, not 0
    fullgrid.append(gridx[imagenumber-1]*gridy[imagenumber-1]) #find total number of crops    #"append" because cant add to empty list
    #save this so we can reconstruct later
    if not os.path.exists('output'): #create output folder if it doesnt exist
        os.makedirs('output')
    a = 0 #a tracks in which collumn we are (horizontal)
    b = 1 #b tracks in which row we are (vertical)
    for imageslice in range (1, fullgrid[imagenumber-1]+1):
        print('Cropping slice: ', imageslice, '/', fullgrid[imagenumber-1], end='\r') #printing with override to show progress
        a = a + 1
        if a > gridx[imagenumber-1]:
            a = 1
            b = b + 1
        x1 = (a-1)*padding #x1 crop coordinate
        x2 = (b-1)*padding #x2 crop coordinate
        y1 = x1 + padding*2
        if y1 > image.size[0]:
            y1 = image.size[0]
        y2 = x2 + padding*2
        if y2 > image.size[1]:
            y2 = image.size[1]
        #debug: print (imageslice,': x1 = ',x1,' , x2 = ',x2,' , y1 = ',y1,' , y2 = ',y2)
        cropped = image.crop ((x1,x2,y1,y2))
        path = 'input/' + str(imagenumber) + '-' + str(imageslice) + '.png'
        cropped.save(path,'PNG') #save cropped image(s)
    sourceImageInputPath = 'input/'+filenames[imagenumber-1]
    sourceImageOutputPath = 'output/'+filenames[imagenumber-1]
    shutil.move(sourceImageInputPath, sourceImageOutputPath) #move source image(s) to output as a backup

print ('') #to end override progress printing style    
print ('Calling the main upscaling script and waiting for it to finish... ')
if upscale == 4: #calling the main script and waiting for it to finish
    retcode = subprocess.call(["python", "test.py", '-i', 'input', '--checkpoint', 'data/checkpoints/proSRGAN_x4.pth', '--scale', '4', '-o', 'output'])
else: 
    retcode = subprocess.call(["python", "test.py", '-i', 'input', '--checkpoint', 'data/checkpoints/proSRGAN_x8.pth', '--scale', '8', '-o', 'output'])


imagenumber = 0
for image in image_list: #go through each image
    imagenumber += 1
    upscaled = Image.new('RGB', (image.size[0]*upscale, image.size[1]*upscale)) #prepare canvas for pasting
    print ('Creating canvas for image', imagenumber, '/', len(image_list), ':' , image.size[0]*upscale, ' x ' ,image.size[1]*upscale)
    pastex = 0
    pastey = 0
    a = 0
    b = 1
    for imageslice in range (1, fullgrid[imagenumber-1]+1): #for each imageslice in current image
        print('Adding slice: ', imageslice, '/', fullgrid[imagenumber-1], end='\r') #printing with override to show progress
        imagename = str(imagenumber) + ('-') + str(imageslice) + ('.png') 
        path = 'output/' + imagename
        path2 = 'input/' + imagename
        im = Image.open(path) #open the corresponding image slice
        a = a + 1 #start counting collumns
        if a > gridx[imagenumber-1]: #after final collumn
            a = 1 
            b = b + 1 #start counting rows
            pastex = 0 #when putting images togheter, paste each first collumn at horizontal coordinate 0
            pastey = pastey+cropped.size[1] #paste next row below previous row
        x1 = upscale*(padding/2) #calculate coordinates for cropping
        x2 = upscale*(padding/2) #in order to remove the padding
        y1 = upscale*(padding*2-padding/2)
        y2 = upscale*(padding*2-padding/2)
        if a == gridx[imagenumber-1]: #crop all the way to the right on the right edge
            y1= upscale*padding*2
        if b == gridy[imagenumber-1]: #crop all the way to the bottom on the bottom edge
            y2= upscale*padding*2
        if a == 1: #crop all the way to the left on the left edge
            x1 = 0
        if b == 1: #crop all the way to the right on the right edge
            x2 = 0
        if y1 > im.size[0]: #clip cropping to maximum resolution
            y1 = im.size[0] #if cropping coordinates are outside of the image
        if y2 > im.size[1]:
            y2 = im.size[1]
        #debug: print (imageslice,': x1 = ',x1,' , x2 = ',x2,' , y1 = ',y1,' , y2 = ',y2)
        cropped = im.crop((x1,x2,y1,y2))
        upscaled.paste(cropped, (pastex,pastey)) #add each image slice to canvas
        pastex = pastex + cropped.size[0] #to add each image slice after previous one
        for retry in range(100): #retry loop to get around windows sometimes denying acces
            try:
                os.remove(path) #delete image slice after we finished adding it
                break
            except:
                print ('')
                print ('delete file failed, retrying...')
        for retry in range(100): #retry loop to get around windows sometimes denying acces
            try:
                os.remove(path2) #delete image slice in input folder as well
                break
            except:
                print ('')
                print ('delete file failed, retrying...')
    pathfinal = 'output/' + str(upscale) + ('x') + ('-') + filenames[imagenumber-1] + ('.png')
    print ('')
    print ('Saving... ')
    upscaled.save(pathfinal,'PNG') #save composite image
    print ('Saved: ', pathfinal)

print ('Finished!')
```

**- Installation:**
Put this script in the root folder right next to test.py. eg: \Anaconda3\envs\proSR\upscale.py 
**- Usage:**
**1)** create "input" folder, eg: ...\Anaconda3\envs\proSR\input\
**2)** put only images you want to upscale in that folder, nothing else.
**3)** instead of running test.py with arguments as you usually would, just run upscale.py (with no arguments)
**4)** your original and upscaled images will appear in ...\Anaconda3\envs\proSR\output\

**-** Default is 4x upscale, change upscale variable to 8 if you want 8x upscale.
**-** Default is 128px padding, size of the overlap between any two slices, which also defines size of slices, so you can lower this if you still don't have enough memory on GPU, but lowering it too much might introduce seams (padding is automatically removed in the process of stitching the image back together after the upscale).
**-** It's made to be used with GAN, but should be trivial to modify to use for not-GAN.

**Comment by fperazzi** [comment]
@Shadetail thanks a lot for your contribution. I suggest to leave it here for the moment. I'm sure other people will find it useful.

**Comment by PPiirainen** [comment]
Also a real beginner here. 


There seesm to be a bug in the code. 
Did as instructed: Placed my pictures into ProSR/input folder and run the upscale.py from ProSP.
Running this  gives me an error: 
FileNotFoundError: [Errno 2] No such file or directory: 'output/1-1.png'
 The script itself seems to me placing  the splitted parts into the /input directory first as the little pieces can be found from the /input directory after the script has halted.

**Comment by Shadetail** [comment]
It might be more clear what's going on if you post the whole console output, but from your description this seems like it could be one of the following, in order of highest likeliehood:
- ProSR encountered an error during upscaling and did not actually upscale the image parts. That's why the script says it cannot find the first upscaled part. (likely) (most likely due to issue with the way ProSR environment is set up)
- There was some kind of problem with calling the ProSR script (test.py) so upscaling never started, so no upscaled parts could be found. (unlikely)
- There was some kind of problem with waiting for ProSR script (test.py) to finish, so the script proceeded to attempt to put together a final image before ProSR had time to upscale all the image pieces. (unlikely)

Script is intended to place pieces in input folder first, then after back-up moving your original image to output folder, hand the pieces over to main script from this project (it automatically calls it so you don't have to), and when the main script (test.py) upscales each piece it creates an upscaled version of it in output directory, and after it's finished upscaling all the pieces, my script resumes, expecting to find all the upscaled pieces in the output directory, and starts putting them together. Then as it puts each piece of the puzzle back together successfully, it deletes the piece in both input and output directories, and when it finished putting all the pieces back together, you should be left with only your original files and their upscaled files in the output directory, and you should find input directory to be empty.

**Comment by stephanedebove** [comment]
@Shadetail thanks a lot for the script! It looks like though, if you zoom a lot on the output image (like 5 to 8 times) that you can actually see the square slices that were used by your script. If you know a workaround I'd be happy to know it!

**Comment by Shadetail** [comment]
Interesting. In the images I used to test it, no seams at all were visible no matter how much I zoomed and looked for them, but it's conceivable that on a certain type of content, some seams might still be visible. In other words, I cannot definitively say that no seams will ever be visible as I don't know if neural network itself uses any kind of local segmenting at all or if it really just processes entire image at once, with each generated pixel having a probability of being influenced by any other source pixel no matter how far away in the image. In case of latter, it might never be possible to completely get rid of seams in 100% of cases using current approach, but in case of former, some amount of padding should in theory help, assuming the amount isn't so big as to cause GPU memory limit issue when processing a single segment.

So I suggest you try running the script with different padding values and see if that makes it any better. Perhaps try setting it a bit larger, for example 192 or 256 (change it by editing the second line of the script).

Other than that, there's not much that can be done, short of adding a feature that softly blends slices together, but that would be a bit above my current skill level, or in other words would require amounts of time I don't current have. If it's a really important image that you really need processed perfectly, you could remove these script lines:

```
for retry in range(100): #retry loop to get around windows sometimes denying access
            try:
                os.remove(path) #delete image slice after we finished adding it
                break
            except:
                print ('')
                print ('delete file failed, retrying...')
```
Which will cause output slices to not be deleted, after which you can manually assemble the slices in photoshop and smoothly blend in between them by creating gradient masks. It would be a lot of work but would yield perfect result.

**Comment by stephanedebove** [comment]
@Shadetail actually your script might not be the culprit, but proSR could be. The square slices I notice are 8 pixels wide if I'm not mistaken. Here is an example below. The first image is my original image, zoomed in 11 times in the top left corner. The second image is the image upscaled 4 times, also zoomed in 11 times. You can clearly see on the second image the square slices, which look like they come from the original pixels.

Maybe @fperazzi know what we could do to avoid these squares?

![image](https://user-images.githubusercontent.com/6358105/50726763-d52b1f00-1111-11e9-9c8c-c44f3d561dce.png)

![image](https://user-images.githubusercontent.com/6358105/50726770-e1af7780-1111-11e9-8be5-a6f874184fc8.png)

**Comment by Shadetail** [comment]
Oh yeah, that's definitely not due to my script. (If it were, you'd see a seam at the midpoint in between two slices, so exactly at the pixel row 192 or on of its multiples, using default settings.) This is just ProSR dreaming up the seams you're seeing as part of the details it came up with to upscale your image. Since in case of dcnn, algorithm is sort of a black box afaik, the only way to address something like this would be to use more or better training data, or training data that's more similar to the type of image you're trying to upscale.

**Comment by fperazzi** [comment]
I think the seems are unavoidable. Some feathering should alleviate the issue.

**Comment by megapro17** [comment]
I spent a lot of time to get this script working with conda env. Replace 64 and 66 line like this:

```
    retcode = subprocess.call(["activate.bat", "proSR", "&&", "python", "test.py", '-i', 'input', '--checkpoint', 'data/checkpoints/proSRGAN_x4.pth', '--scale', '4', '-o', 'output'])
    retcode = subprocess.call(["activate.bat", "proSR", "&&", "python", "test.py", '-i', 'input', '--checkpoint', 'data/checkpoints/proSRGAN_x8.pth', '--scale', '8', '-o', 'output'])
```
