### ISSUE TITLE
Batch Size and multi-GPU?

### ISSUE THREAD

**Issue by MaxBareiss** [fperazzi/proSR#25]
What does the batch size setting do? It looks like setting the batch size higher doesn't make the code run any faster (time per iter) or reduce the number of iterations per epoch. What is the benefit of running the code on multiple GPUs?

**Comment by fperazzi** [comment]
`batch_size` increases the size of the batch, but also increases the size of the dataset (see code below) and that is why the number of epochs is not changing. It can be fixed by do not increasing the size of the dataset and instead increasing the number of epochs.

```
# progressive_loader.py
            self.dataset.target_fns = self.dataset.target_fns * batch_size
            self.dataset.source_fns = self.dataset.source_fns * batch_size
```
