### ISSUE TITLE
Mean and STD

### ISSUE THREAD

**Issue by AshwinKumarVijay** [fperazzi/proSR#29]
I'm calculating the same mean as you, but I'm not seeing the same standard deviation as you used. I'm wondering how you calculated it.

**Comment by fperazzi** [comment]
Standard deviation is set empirically to 1.0/255.0 such that input floating
point images in range [0,1] are transformed to range [-127.5, 127.5].

**Comment by yifita** [comment]
> I'm calculating the same mean as you, but I'm not seeing the same standard deviation as you used. I'm wondering how you calculated it.

We are using the same mean and std as the EDSR paper. 
https://github.com/LimBee/NTIRE2017
