### ISSUE TITLE
8bit to 16bit

### ISSUE THREAD

**Issue by formidablefrank** [fperazzi/proSR#30]
Hi guys, I was able to train images of 16bit unsigned PNG type. However when I try to test some images the outputs were still 8bit. I also noted that the training set images you used (DIV2K, etc) were 8bit. I also noted that Line 145 of `test.py` contains the image save function.

What parts of the codebase should be modified so that it outputs images of 16bit PNG? Will you be implementing this feature? Thank you.

**Comment by fperazzi** [comment]
Internally we use 32-bit floating point precision, but the function
converting tensors to images (tensor2im) cast the output of the network to
8-bit uint. So you need to comment out that line.

Federico

**Comment by formidablefrank** [comment]
Hi! What I did was to change the following lines on `lib/proSR/utils/misc.py`:

```python
image_numpy = (np.transpose(image_numpy,
                                (1, 2, 0)) * stddev + np.array(mean)) * 255.0
image_numpy = image_numpy.clip(0, 255)
return np.around(image_numpy).astype(np.uint8)
```

to

```python
image_numpy = (np.transpose(image_numpy,
                                (1, 2, 0)) * stddev + np.array(mean)) * 65535.0
image_numpy = image_numpy.clip(0, 65535)
return np.around(image_numpy).astype(np.uint16)
```

So that the image tensor will be converted to 16uint.
