### ISSUE TITLE
Issue with _worker_manager_loop

### ISSUE THREAD

**Issue by eruizvelasco** [fperazzi/proSR#31]
FYI in case anyone has run into this issue... I tried to run prosr with my the latest version of pytorch I compiled on mac OS and there was problem with _worker_manager_loop in the prosr/data/multiproc.py file line 103. 

It turns out the function that does the work in the latest version of torch/utils/data/dataloader.py is called now _pin_memory_loop and it seems to work for me. 

I simply replaced the code in line #103 from _worker_manager_loop in prosr/data/multiproc.py to use _pin_memory_loop instead:
before:
               self.worker_manager_thread = threading.Thread(
                    target=_worker_manager_loop,
                   args=(self.worker_result_queue, self.data_queue, self.done_event, self.pin_memory,
                          maybe_device_id))
after:
                self.worker_manager_thread = threading.Thread(
                    target=_pin_memory_loop,
                    args=(self.worker_result_queue, self.data_queue, maybe_device_id, self.done_event))

**Comment by darylfung96** [comment]
Thank you!
