### ISSUE TITLE
proSRGAN training

### ISSUE THREAD

**Issue by gitman88** [fperazzi/proSR#32]
What is wrong with the following command when trying to train the proSRGAN model?

`python train_gan.py --checkpoint data/checkpoints/proSRGAN_x4.pth --output data/checkpoints/proSRGAN_checkpoints
`
It generates the error

`FileNotFoundError: [Errno 2] No such file or directory: 'data/checkpoints/proSRGAN_x4.pth_net_G.pth'`

Which obviously is correct since I have no such model. Is it possible to download the _net_G.pth models? Or am I missing something?

Thanks in advance!

**Comment by eruizvelasco** [comment]
I think this command is trying to resume a previous training session

**Comment by yaceben** [comment]
@gitman88  remove the .pth in checkpoint parameter. You should have proSRGAN_x4_net_G.pth and proSRGAN_x4_optim_G.pth in your checkpoint directory I think. As for final models, I'm not sure, didn't have the time to check the code yet.

**Comment by fperazzi** [comment]
@yaceben @gitman88, yes we do provide pre-trained models. The code is appending `_net_G.pth` to the command line argument `--checkpoint`. I'll fix the issue soon, meanwhile, as a quick workaround rename `proSRGAN_x4.pth` to `proSRGAN_x4_net_G.pth and execute:

`python train_gan.py --checkpoint data/checkpoints/proSRGAN_x4 --output data/checkpoints/proSRGAN_checkpoints 
`

**Comment by yaceben** [comment]
Thanks for the update and instructions @fperazzi !

cheers
