### ISSUE TITLE
Missing repo file: lib/prosr/data/chunks.py

### ISSUE THREAD

**Issue by samueldana** [fperazzi/proSR#37]
Commit 1328704 (in lib/prosr/data/__init__.py:2) seems to reference a 'chunks.py', that is not included in the repository.

**Comment by bonakdarf92** [comment]
yeah seems you forgot to push chunks.py

**Comment by bonakdarf92** [comment]
@samueldana Ok I found it ... seems to be in dev branch

**Comment by samueldana** [comment]
@bonakdarf92 Thank you for the info, will check it out.

**Comment by fperazzi** [comment]
pushed.
