### ISSUE TITLE
RuntimeError: The size of tensor a (320) must match the size of tensor b (1280) at non-singleton dimension 3

### ISSUE THREAD

**Issue by aligoglos** [fperazzi/proSR#40]
I tried script : `python test.py -i TestImages/1.jpg --checkpoint Weigths/proSR.pth -o Results/ --scale 4` but but below error occured :
```
2019-04-09 07:07:17: Saving images in: Results/
Traceback (most recent call last):
  File "test.py", line 151, in <module>
    input = data['input'] + data['bicubic']
RuntimeError: The size of tensor a (320) must match the size of tensor b (1280) at non-singleton dimension 3
```
my input shape is (3, 320 ,320)

**Comment by albusdemens** [comment]
HI @aligoglos , have you found a solution for this? Same error here

**Comment by albusdemens** [comment]
My solution: have a look at the `net_g.pth` (which gives me another error, but at least it's a step forward).

**Comment by aligoglos** [comment]
i tried but couldn't  fixed that.first i change

input = data['input'] + data['bicubic']

to
input = data['bicubic']

but i got this error:
AttributeError: 'ProSR' object has no attribute 'predict'

send me solution if you found it please. thanks.

**Comment by fperazzi** [comment]
Fixed!
