### ISSUE TITLE
Output Images are downscaled  instead of being upscaled

### ISSUE THREAD

**Issue by ajinkya933** [fperazzi/proSR#44]
I tried proSR GAN here is my command:

<img width="914" alt="Screenshot 2019-05-12 at 11 10 09 AM" src="https://user-images.githubusercontent.com/17012391/57578285-c29d6980-74a6-11e9-929f-8f5cf19bed89.png">

I observed that in the output I get Downscaled images with low size in MB, Instead of being upscaled.Here is my output
<img width="1437" alt="Screenshot 2019-05-12 at 11 14 29 AM" src="https://user-images.githubusercontent.com/17012391/57578308-40fa0b80-74a7-11e9-93eb-e8047202d439.png">

On the right hand side is my output and and on left hand side is the input high res images.
Am I doing something wrong ? why is by output being downscaled instead of being upscaled ?

**Comment by JBrownemoore** [comment]
by the looks of your directory you are using the high resolution photos (DIVK2_valid_HR). This is just a hunch but maybe that is what is going on here.

**Comment by JBrownemoore** [comment]
by the looks of your directory you are using the high resolution photos (DIVK2_valid_HR). This is just a hunch but maybe that is what is going on here.

**Comment by yifita** [comment]
First off, you need to check the actual dimension instead of the size of the image :)

**Comment by ajinkya933** [comment]
I switched to another technique to get superesolution
