### ISSUE TITLE
mkdir string issue

### ISSUE THREAD

**Issue by pusalieth** [fperazzi/proSR#54]
I don't know if it's just a wsl on windows thing, but in the get_data.sh, line 4 the current file uses:
`mkdir -p $DATADIR/datasets $DATADIR/checkpoints`
On wsl, the forward slashes are interpreted literally, and creates a directory with weird unicode chars. This could easily be fixed by using instead:
`mkdir -p $DATADIR'/datasets' $DATADIR'/checkpoints'`
This way the entire line is interpreted as a single string.

**Comment by pusalieth** [comment]
turns out the entire script is interpreted that way. I don't know if you want to use different formatting for the entire script or not. If changed, it should work on all systems, regardless.

**Comment by pusalieth** [comment]
I'm working on to figure out what's going on. I'll make a pull request once I have a solution.

**Comment by pusalieth** [comment]
So, it looks like the problem was hidden chars in the string path that weren't showing up at least in my editor. (VS code) I just copied the raw text, and resaved the file, was all that was necessary.

**Comment by pusalieth** [comment]
So, I believe I found the specific issue. It looks like the file contained an EOF marker. Pull request for fix is here. I also added the dirs to gitignore.

https://github.com/fperazzi/proSR/pull/55

**Comment by fperazzi** [comment]
Great thanks, pull request merged.
